application: ascii-art-007
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /(.*\.(gif|png|jpg))
  static_files: /
  upload: /(.*\.(gif|png|jpg))

- url: /
  script: main.app
- url: /logout
  script: main.app
- url: /Upload
  script: main.app
- url: /Img
  script: ASCII.app
- url: /Download
  script: ASCII.app
- url: /Imgfromurl
  script: ASCII.app
- url: /Downloadfromurl
  script: ASCII.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: PIL
  version: latest
